### ISSUE TITLE
Browserify plugin

### ISSUE THREAD

**Issue by letmaik** [aMarCruz/jscc#1]
This is really cool! Any chance for a browserify plugin? I'd like to use jscc within [budo](https://github.com/mattdesl/budo) during development which uses browserify under the hood.

**Comment by aMarCruz** [comment]
@letmaik,  I don't know how browserify works but  I'll take a look at this asap,

**Comment by aMarCruz** [comment]
@letmaik , you can install [jsccify](https://github.com/aMarCruz/jsccify) now from npm.
This has no support for source map yet.
I don't have any setup with browserify but I hope works to you, please test it.

Plugins for Rollup and Brunch (my blunders) exists, [rollup-plugin-jscc](https://github.com/aMarCruz/rollup-plugin-jscc) and [jscc-brunch](https://github.com/aMarCruz/jscc-brunch) has all the features of jscc.

**Comment by letmaik** [comment]
Thanks for that. Why not do automated testing via Travis CI? Should be 
easy with a npm project that then gets browserified with your transform. 
You could check whether some special string exists in the output that 
your transform would conditionally include or omit.

**Comment by aMarCruz** [comment]
@letmaik that would be great, maybe with some [examples](https://github.com/aMarCruz/jscc/wiki/Examples), but I have not enough time.

This repo has 100% coverage but has an agnostic codebase. It does not involve streams nor is tested in browsers, as jscc is just a preprocessor designed for node that reads `version` from package.json, unless you pass a `_VERSION` value (I think it will be necessary to check the environment).

I will add sourcemap support to jsccify asap, and then the tests if there is enough interest in the package...

PRs are welcome of course.

I'm closing this issue now, your feedback in the jsccify repo will be appreciated.

**Comment by letmaik** [comment]
I just tried it, works great! :)
