### ISSUE TITLE
Use with imports

### ISSUE THREAD

**Issue by smth** [aMarCruz/jscc#9]
Hi

I was trying to do something like:

```js
import thing from '../my-thing.js';

//#set _FOO = thing.object[key]
```

But am getting `thing is not defined in expression "thing.object[key]".
Is it possible to make this work?

**Comment by aMarCruz** [comment]
@smth , you are trying to get a runtime value with a compile-time tool.

I mean, jscc runs in its own space at compile time and does not know anything about the values of variables in the code it processes.

It uses JavaScript to decide which code block to include or exclude, or which text to replace in the code, but treats these code as simple text, does not evaluate it.

This behavior is similar to that of the C preprocessor, but it may be a strange concept for the JS world. I will put a note in the Readme about it, when have the time :)

Closing the issue now, thanks for your feedback.

**Comment by aMarCruz** [comment]
This must works (I don't test it):

Read the object at compile time and send it to jscc in the values property of the options.

```js
import thing from '../my-thing.js';

const processedCode = jscc(code, {
  values: { _THING: thing }
  // now `thing` is visible at compile-time
})
```

If you are using a plugin, for example w/rollup, do that in your rollup.config.js

**Comment by smth** [comment]
Yes, that was what I was looking for; and it works, thanks!

Note: comment should maybe say "now `_THING` is visible..."
